baseURL = 'https://photography-songshgeo.vercel.app/'
languageCode = 'en-us'
title = 'Photography by SongshGeo'
theme = 'gallery'

# Content settings
[pagination]
  pagerSize = 100
enableRobotsTXT = true
enableGitInfo = true

# Theme settings
[params]
  description = 'A photography gallery showcasing the work of SongshGeo'
  copyright = '© 2025 SongshGeo. All rights reserved.'
  defaultTheme = 'auto'  # 'light', 'dark', or 'auto'
  
  [params.author]
    name = 'Shuang Song (SongshGeo)'
    email = 'SongshGeo@gmail.com'
  
  # Social icons
  [params.socialIcons]
    github = 'https://github.com/SongshGeo'
    email = 'mailto:SongshGeo@gmail.com'
    # Add academic and blog links
    website = 'https://songshgeo.com/'
    cv = 'https://cv.songshgeo.com/'

# Image processing
[imaging]
  # Default resample filter used for resizing
  resampleFilter = 'lanczos'
  # Default JPEG quality
  quality = 85
  # Anchor used when cropping pictures
  anchor = 'smart'
  # Default background color
  bgColor = '#ffffff'

# Related content configuration
[related]
  includeNewer = true
  threshold = 10
  toLower = false
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'categories'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 10
  [[related.indices]]
    applyFilter = false
    cardinalityThreshold = 0
    name = 'tags'
    pattern = ''
    toLower = false
    type = 'basic'
    weight = 50

# Taxonomies
[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

# Markup configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
