#!/usr/bin/env python3
"""Build the curated home-gallery data file from photo star ratings.

Star ratings live in XMP (`XMP-xmp:Rating`), which Hugo cannot read at build
time. This script reads them with exiftool and writes `data/featured_photos.yaml`,
a list of the high-rated photos that `layouts/partials/home-gallery.html` renders
as one cross-trip justified gallery on the home page.

Usage:
    python3 scripts/build_featured.py [min_rating]

    min_rating  Minimum star rating to include (default: 3).

Re-run this whenever you change ratings, then commit the updated data file.
"""

import json
import os
import subprocess
import sys

CONTENT_ROOT = "content/trips"
OUTPUT = "data/featured_photos.yaml"
DEFAULT_MIN_RATING = 3


def main() -> int:
    min_rating = int(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_MIN_RATING

    repo = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(repo)

    if not os.path.isdir(CONTENT_ROOT):
        print(f"error: {CONTENT_ROOT} not found (run from the repo root)", file=sys.stderr)
        return 1

    # One batched exiftool pass over the whole trips tree.
    proc = subprocess.run(
        [
            "exiftool", "-j", "-q", "-r",
            "-Rating", "-Title", "-ImageDescription",
            "-DateTimeOriginal", "-CreateDate",
            "-ext", "jpg", "-ext", "jpeg", "-ext", "heic",
            CONTENT_ROOT,
        ],
        capture_output=True, text=True,
    )
    if proc.returncode != 0 and not proc.stdout.strip():
        print(proc.stderr, file=sys.stderr)
        return 1

    records = json.loads(proc.stdout or "[]")

    seen = set()
    items = []
    for r in records:
        rating = r.get("Rating")
        if rating is None or int(rating) < min_rating:
            continue
        source = r["SourceFile"]  # e.g. content/trips/China/Sichuan/2024....jpg
        rel = os.path.relpath(source, "content")  # trips/China/Sichuan/2024....jpg
        page = os.path.dirname(rel).replace(os.sep, "/")  # trips/China/Sichuan
        src = os.path.basename(rel)
        if src in seen:  # dedupe (e.g. the hero cover that also lives in a trip)
            continue
        seen.add(src)
        date = r.get("DateTimeOriginal") or r.get("CreateDate") or ""
        title = r.get("Title") or r.get("ImageDescription") or ""
        # Drop camera-default junk descriptions (e.g. "OLYMPUS DIGITAL CAMERA").
        if "DIGITAL CAMERA" in title.upper():
            title = ""
        items.append({
            "page": page,
            "src": src,
            "rating": int(rating),
            "date": str(date),
            "title": str(title).strip(),
        })

    # Highest-rated first, then newest.
    items.sort(key=lambda i: (-i["rating"], i["date"]), reverse=False)
    items.sort(key=lambda i: i["date"], reverse=True)
    items.sort(key=lambda i: i["rating"], reverse=True)

    os.makedirs("data", exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as fh:
        fh.write(f"# Generated by scripts/build_featured.py (Rating >= {min_rating}). Do not edit by hand.\n")
        for i in items:
            fh.write(f"- page: {json.dumps(i['page'])}\n")
            fh.write(f"  src: {json.dumps(i['src'])}\n")
            fh.write(f"  rating: {i['rating']}\n")
            fh.write(f"  date: {json.dumps(i['date'])}\n")
            fh.write(f"  title: {json.dumps(i['title'])}\n")

    counts = {}
    for i in items:
        counts[i["rating"]] = counts.get(i["rating"], 0) + 1
    breakdown = ", ".join(f"{k}★×{counts[k]}" for k in sorted(counts, reverse=True))
    print(f"Wrote {len(items)} photos to {OUTPUT} (Rating >= {min_rating}) — {breakdown}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
